import type { NextPage } from 'next'
import {useState, useEffect} from 'react';
import Head from 'next/head'
import Header from '../components/Header/Header'
import Section1 from '../components/Section/Main/Section1'
import Section2 from '../components/Section/Main/Section2'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Section1/>
        <Section2/>
      <Header/>
    </div>
  )
}

export default Home
